version: "3"
services:
  database:
    image: mariadb:10
    container_name : database
    ports:
      - 3306:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
  application:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/wematch?useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database
